# Configuration Netlify pour le CV professionnel
[build]
  # Dossier à publier (racine dans ce cas)
  publish = "."
  
  # Commande de build (optionnelle car on a du HTML statique)
  command = "echo 'Build complete - HTML/CSS/JS ready'"

[build.environment]
  # Variables d'environnement si nécessaire
  NODE_VERSION = "18"

# Redirections et réécritures d'URL
[[redirects]]
  # Redirection de l'ancien CV si existant
  from = "/old-cv/*"
  to = "/"
  status = 301

[[redirects]]
  # Gestion des erreurs 404
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com;"
    
    # Performance
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Disposition = "inline; filename=cv-antonie-donfack.pdf"

# Configuration des formulaires Netlify (si vous ajoutez un formulaire de contact)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugin pour l'optimisation des images
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Fonctions serverless (optionnel pour contact form)
[functions]
  directory = "netlify/functions"